# Generated by compozit.ps1 - do not edit. Rewritten on every start.
# Supervising loop for: Queue worker 1
$ErrorActionPreference = 'Continue'
Set-Location 'D:\Projects\laragon\www\compozit-suite'
$exeArgs = @('artisan', 'queue:work', '--tries=3', '--timeout=90', '--sleep=3', '--max-time=3600')
while (-not (Test-Path 'D:\Projects\laragon\www\compozit-suite\deploy\run\stopping.flag')) {
    & 'D:\Projects\laragon\bin\php\php-8.4.12-nts-Win32-vs17-x64\php.exe' @exeArgs *>> 'D:\Projects\laragon\www\compozit-suite\storage\logs\queue-1.log'
    if (Test-Path 'D:\Projects\laragon\www\compozit-suite\deploy\run\stopping.flag') { break }
    Start-Sleep -Seconds 2
}
