# Generated by compozit.ps1 - do not edit. Rewritten on every start.
# Supervising loop for: Task scheduler
$ErrorActionPreference = 'Continue'
Set-Location 'D:\Projects\laragon\www\compozit-suite'
$exeArgs = @('artisan', 'schedule:work')
while (-not (Test-Path 'D:\Projects\laragon\www\compozit-suite\deploy\run\stopping.flag')) {
    & 'D:\Projects\laragon\bin\php\php-8.4.12-nts-Win32-vs17-x64\php.exe' @exeArgs *>> 'D:\Projects\laragon\www\compozit-suite\storage\logs\scheduler.log'
    if (Test-Path 'D:\Projects\laragon\www\compozit-suite\deploy\run\stopping.flag') { break }
    Start-Sleep -Seconds 2
}
