# Generated by compozit.ps1 - do not edit. Rewritten on every start.
# Supervising loop for: Web server (Apache)
$ErrorActionPreference = 'Continue'
Set-Location 'D:\Projects\laragon\www\compozit-suite'
$exeArgs = @('-d', 'D:\Projects\laragon\bin\apache\httpd-2.4.66-260223-Win64-VS18')
while (-not (Test-Path 'D:\Projects\laragon\www\compozit-suite\deploy\run\stopping.flag')) {
    & 'D:\Projects\laragon\bin\apache\httpd-2.4.66-260223-Win64-VS18\bin\httpd.exe' @exeArgs *>> 'D:\Projects\laragon\www\compozit-suite\storage\logs\apache.log'
    if (Test-Path 'D:\Projects\laragon\www\compozit-suite\deploy\run\stopping.flag') { break }
    Start-Sleep -Seconds 2
}
